### ISSUE TITLE
Inference speed

### ISSUE THREAD

**Issue by saskra** [mindflow-institue/DermoSegDiff#2]
The inference, i.e. the application of a trained model to test images, is very slow for me. Are there any ways to speed it up?

**Comment by bravo-hq** [comment]
Dear @saskra,

Thank you for reaching out regarding the performance concerns with inference times in our DDPM-based model.

Just to let you know, the inherent nature of Denoising Diffusion Probabilistic Models (DDPMs) requires the completion of each diffusion step sequentially, which can be time-intensive. The duration of the inference process is influenced by two primary factors: the total number of diffusion steps implemented and the dimensions of the images within your dataset.

We are aware of the importance of efficiency in your work, so we are actively exploring ways to expedite this process. Our team is developing an update to incorporate Denoising Diffusion Implicit Models (DDIMs), which we anticipate will offer improved inference speeds.

In the interim, I highly recommend consulting the following comprehensive survey, which provides an in-depth examination of various diffusion model architectures, specifically addressing the challenge of extended inference times:

[Diffusion models in medical imaging: A comprehensive survey](https://doi.org/10.1016/j.media.2023.102846)

This resource may offer valuable insights and alternative approaches to mitigate the latency you are currently experiencing.

We appreciate your patience and understanding as we endeavor to enhance our model's performance. If you have further questions or need additional assistance, please do not hesitate to contact us.

Sincerely,
Yousef Sadegheih
