### ISSUE TITLE
CUDA Plugin Conflicts

### ISSUE THREAD

**Issue by Sajjadkhani** [mindflow-institue/DermoSegDiff#4]
In testing DermoSegDiff for some images in googleColab I am experiencing CUDA plugin conflicts (cuDNN, cuFFT, cuBLAS). Here is the error file. 
[error.txt](https://github.com/xmindflow/DermoSegDiff/files/14052603/error.txt)

**Comment by bravo-hq** [comment]
Dear @Sajjadkhani,

Thank you for reaching out to us with your issue. Upon reviewing the error logs you've provided, it appears that the core problem is related to a missing file in your project directory. The **RuntimeError** indicated in the PyTorch traceback points to a 'file not found' issue, specifically the absence of **'output/dataset/masks/ISIC_0024343_segmentation.png'**.

This error typically occurs under two circumstances: either the file does not actually exist in the specified location, or there is a misconfiguration in the file path within your code. I would recommend verifying the existence of this file in the path mentioned. If the file is indeed there, the next step would be to check your code for any potential path misconfigurations. It's crucial to ensure that the directory structure in your project aligns with the paths expected in the code.

Please let us know if this resolves the issue or if you need further assistance. 

Sincerely,
Yousef Sadegheih

**Comment by Sajjadkhani** [comment]
Both for testing and training, I encountered the issue where a required segmentation file (masks/ISIC_0025139_segmentation.png) is missing, preventing the code from running as expected. I initially thought such files would be generated during training, but it seems this is not the case. Could you provide guidance on how to obtain or generate this file?

Additionally, there seems to be a package dependency inconsistency. Following the requirements.txt leads to multiple dependency errors, but updating to the latest versions causes the mentioned file not found error. It suggests the repository may not be fully compatible with newer package versions. Can you confirm or advise on this?

Thanks for your assistance.
Sajjad
