### ISSUE TITLE
testing error

### ISSUE THREAD

**Issue by YasuoFly** [mindflow-institue/DermoSegDiff#6]
When i testing with `dsd_01.yaml`, I meet the error.
![image](https://github.com/xmindflow/DermoSegDiff/assets/76839625/065aff0f-d0bd-4506-88f5-da1040fced6b)
![image](https://github.com/xmindflow/DermoSegDiff/assets/76839625/0cf84375-503f-44e8-bbb3-380bf17ccf12)

**Comment by bravo-hq** [comment]
Dear @YasuoFly,

Thanks for contacting us. It seems that the Albumentations API which is used for augmentation, has been changed. You can easily comment out this augmentation, and there should not be significant changes to the output. Or you can fix the `std` variable to 0.1. 

Let me know if you still have a problem. 

Sincerely,
Yousef Sadegheih
